export const pokemon = [
    {
        id: 1,
        name: "bulbasaur",
        types: ["grass", "poison"],
        stats: {
            hp: 45,
            attack: 49,
            defense: 49,
            "special-attack": 65,
            "special-defense": 65,
            speed: 45,
        },
        height: 7,
        weight: 69,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/1.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
    },
    {
        id: 2,
        name: "ivysaur",
        types: ["grass", "poison"],
        stats: {
            hp: 60,
            attack: 62,
            defense: 63,
            "special-attack": 80,
            "special-defense": 80,
            speed: 60,
        },
        height: 10,
        weight: 130,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/2.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png",
    },
    {
        id: 3,
        name: "venusaur",
        types: ["grass", "poison"],
        stats: {
            hp: 80,
            attack: 82,
            defense: 83,
            "special-attack": 100,
            "special-defense": 100,
            speed: 80,
        },
        height: 20,
        weight: 1000,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/3.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png",
    },
    {
        id: 4,
        name: "charmander",
        types: ["fire"],
        stats: {
            hp: 39,
            attack: 52,
            defense: 43,
            "special-attack": 60,
            "special-defense": 50,
            speed: 65,
        },
        height: 6,
        weight: 85,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/4.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
    },
    {
        id: 5,
        name: "charmeleon",
        types: ["fire"],
        stats: {
            hp: 58,
            attack: 64,
            defense: 58,
            "special-attack": 80,
            "special-defense": 65,
            speed: 80,
        },
        height: 11,
        weight: 190,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/5.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png",
    },
    {
        id: 6,
        name: "charizard",
        types: ["fire", "flying"],
        stats: {
            hp: 78,
            attack: 84,
            defense: 78,
            "special-attack": 109,
            "special-defense": 85,
            speed: 100,
        },
        height: 17,
        weight: 905,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/6.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png",
    },

    {
        id: 7,
        name: "squirtle",
        types: ["water"],
        stats: {
            hp: 44,
            attack: 48,
            defense: 65,
            "special-attack": 50,
            "special-defense": 64,
            speed: 43,
        },
        height: 5,
        weight: 90,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/7.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
    },
    {
        id: 8,
        name: "wartortle",
        types: ["water"],
        stats: {
            hp: 59,
            attack: 63,
            defense: 80,
            "special-attack": 65,
            "special-defense": 80,
            speed: 58,
        },
        height: 10,
        weight: 225,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/8.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png",
    },
    {
        id: 9,
        name: "blastoise",
        types: ["water"],
        stats: {
            hp: 79,
            attack: 83,
            defense: 100,
            "special-attack": 85,
            "special-defense": 105,
            speed: 78,
        },
        height: 16,
        weight: 855,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/9.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png",
    },
    {
        id: 10,
        name: "caterpie",
        types: ["bug"],
        stats: {
            hp: 45,
            attack: 30,
            defense: 35,
            "special-attack": 20,
            "special-defense": 20,
            speed: 45,
        },
        height: 3,
        weight: 29,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png",
    },
    {
        id: 11,
        name: "metapod",
        types: ["bug"],
        stats: {
            hp: 50,
            attack: 20,
            defense: 55,
            "special-attack": 25,
            "special-defense": 25,
            speed: 30,
        },
        height: 7,
        weight: 99,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/11.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png",
    },
    {
        id: 12,
        name: "butterfree",
        types: ["bug", "flying"],
        stats: {
            hp: 60,
            attack: 45,
            defense: 50,
            "special-attack": 90,
            "special-defense": 80,
            speed: 70,
        },
        height: 11,
        weight: 320,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/12.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png",
    },
    {
        id: 13,
        name: "weedle",
        types: ["bug", "poison"],
        stats: {
            hp: 40,
            attack: 35,
            defense: 30,
            "special-attack": 20,
            "special-defense": 20,
            speed: 50,
        },
        height: 3,
        weight: 32,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/13.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png",
    },
    {
        id: 14,
        name: "kakuna",
        types: ["bug", "poison"],
        stats: {
            hp: 45,
            attack: 25,
            defense: 50,
            "special-attack": 25,
            "special-defense": 25,
            speed: 35,
        },
        height: 6,
        weight: 100,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/14.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png",
    },
    {
        id: 15,
        name: "beedrill",
        types: ["bug", "poison"],
        stats: {
            hp: 65,
            attack: 90,
            defense: 40,
            "special-attack": 45,
            "special-defense": 80,
            speed: 75,
        },
        height: 10,
        weight: 295,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/15.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png",
    },
    {
        id: 16,
        name: "pidgey",
        types: ["normal", "flying"],
        stats: {
            hp: 40,
            attack: 45,
            defense: 40,
            "special-attack": 35,
            "special-defense": 35,
            speed: 56,
        },
        height: 3,
        weight: 18,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/16.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png",
    },
    {
        id: 17,
        name: "pidgeotto",
        types: ["normal", "flying"],
        stats: {
            hp: 63,
            attack: 60,
            defense: 55,
            "special-attack": 50,
            "special-defense": 50,
            speed: 71,
        },
        height: 11,
        weight: 300,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/17.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png",
    },
    {
        id: 18,
        name: "pidgeot",
        types: ["normal", "flying"],
        stats: {
            hp: 83,
            attack: 80,
            defense: 75,
            "special-attack": 70,
            "special-defense": 70,
            speed: 101,
        },
        height: 15,
        weight: 395,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/18.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png",
    },
    {
        id: 19,
        name: "rattata",
        types: ["normal"],
        stats: {
            hp: 30,
            attack: 56,
            defense: 35,
            "special-attack": 25,
            "special-defense": 35,
            speed: 72,
        },
        height: 3,
        weight: 35,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/19.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png",
    },
    {
        id: 20,
        name: "raticate",
        types: ["normal"],
        stats: {
            hp: 55,
            attack: 81,
            defense: 60,
            "special-attack": 50,
            "special-defense": 70,
            speed: 97,
        },
        height: 7,
        weight: 185,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/20.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png",
    },
    {
        id: 21,
        name: "spearow",
        types: ["normal", "flying"],
        stats: {
            hp: 40,
            attack: 60,
            defense: 30,
            "special-attack": 31,
            "special-defense": 31,
            speed: 70,
        },
        height: 3,
        weight: 20,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/21.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png",
    },
    {
        id: 22,
        name: "fearow",
        types: ["normal", "flying"],
        stats: {
            hp: 65,
            attack: 90,
            defense: 65,
            "special-attack": 61,
            "special-defense": 61,
            speed: 100,
        },
        height: 12,
        weight: 380,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/22.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png",
    },
    {
        id: 23,
        name: "ekans",
        types: ["poison"],
        stats: {
            hp: 35,
            attack: 60,
            defense: 44,
            "special-attack": 40,
            "special-defense": 54,
            speed: 55,
        },
        height: 20,
        weight: 69,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/23.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png",
    },
    {
        id: 24,
        name: "arbok",
        types: ["poison"],
        stats: {
            hp: 60,
            attack: 95,
            defense: 69,
            "special-attack": 65,
            "special-defense": 79,
            speed: 80,
        },
        height: 35,
        weight: 650,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/24.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png",
    },
    {
        id: 25,
        name: "pikachu",
        types: ["electric"],
        stats: {
            hp: 35,
            attack: 55,
            defense: 40,
            "special-attack": 50,
            "special-defense": 50,
            speed: 90,
        },
        height: 4,
        weight: 60,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/25.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
    },
    {
        id: 26,
        name: "raichu",
        types: ["electric"],
        stats: {
            hp: 60,
            attack: 90,
            defense: 55,
            "special-attack": 90,
            "special-defense": 80,
            speed: 110,
        },
        height: 8,
        weight: 300,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/26.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png",
    },
    {
        id: 27,
        name: "sandshrew",
        types: ["ground"],
        stats: {
            hp: 50,
            attack: 75,
            defense: 85,
            "special-attack": 20,
            "special-defense": 30,
            speed: 40,
        },
        height: 6,
        weight: 120,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/27.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png",
    },
    {
        id: 28,
        name: "sandslash",
        types: ["ground"],
        stats: {
            hp: 75,
            attack: 100,
            defense: 110,
            "special-attack": 45,
            "special-defense": 55,
            speed: 65,
        },
        height: 10,
        weight: 295,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/28.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png",
    },
    {
        id: 29,
        name: "nidoran-f",
        types: ["poison"],
        stats: {
            hp: 55,
            attack: 47,
            defense: 52,
            "special-attack": 40,
            "special-defense": 40,
            speed: 41,
        },
        height: 4,
        weight: 70,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/29.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png",
    },
    {
        id: 30,
        name: "nidorina",
        types: ["poison"],
        stats: {
            hp: 70,
            attack: 62,
            defense: 67,
            "special-attack": 55,
            "special-defense": 55,
            speed: 56,
        },
        height: 8,
        weight: 200,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/30.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png",
    },
    {
        id: 31,
        name: "nidoqueen",
        types: ["poison", "ground"],
        stats: {
            hp: 90,
            attack: 92,
            defense: 87,
            "special-attack": 75,
            "special-defense": 85,
            speed: 76,
        },
        height: 13,
        weight: 600,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/31.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png",
    },
    {
        id: 32,
        name: "nidoran-m",
        types: ["poison"],
        stats: {
            hp: 46,
            attack: 57,
            defense: 40,
            "special-attack": 40,
            "special-defense": 40,
            speed: 50,
        },
        height: 5,
        weight: 90,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/32.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png",
    },
    {
        id: 33,
        name: "nidorino",
        types: ["poison"],
        stats: {
            hp: 61,
            attack: 72,
            defense: 57,
            "special-attack": 55,
            "special-defense": 55,
            speed: 65,
        },
        height: 9,
        weight: 195,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/33.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/33.png",
    },
    {
        id: 34,
        name: "nidoking",
        types: ["poison", "ground"],
        stats: {
            hp: 81,
            attack: 102,
            defense: 77,
            "special-attack": 85,
            "special-defense": 75,
            speed: 85,
        },
        height: 14,
        weight: 620,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/34.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png",
    },
    {
        id: 35,
        name: "clefairy",
        types: ["fairy"],
        stats: {
            hp: 70,
            attack: 45,
            defense: 48,
            "special-attack": 60,
            "special-defense": 65,
            speed: 35,
        },
        height: 6,
        weight: 75,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/35.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png",
    },
    {
        id: 36,
        name: "clefable",
        types: ["fairy"],
        stats: {
            hp: 95,
            attack: 70,
            defense: 73,
            "special-attack": 95,
            "special-defense": 90,
            speed: 60,
        },
        height: 13,
        weight: 400,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/36.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/36.png",
    },
    {
        id: 37,
        name: "vulpix",
        types: ["fire"],
        stats: {
            hp: 38,
            attack: 41,
            defense: 40,
            "special-attack": 50,
            "special-defense": 65,
            speed: 65,
        },
        height: 6,
        weight: 99,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/37.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png",
    },
    {
        id: 38,
        name: "ninetales",
        types: ["fire"],
        stats: {
            hp: 73,
            attack: 76,
            defense: 75,
            "special-attack": 81,
            "special-defense": 100,
            speed: 100,
        },
        height: 11,
        weight: 199,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/38.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png",
    },
    {
        id: 39,
        name: "jigglypuff",
        types: ["normal", "fairy"],
        stats: {
            hp: 115,
            attack: 45,
            defense: 20,
            "special-attack": 45,
            "special-defense": 25,
            speed: 20,
        },
        height: 5,
        weight: 55,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/39.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png",
    },
    {
        id: 40,
        name: "wigglytuff",
        types: ["normal", "fairy"],
        stats: {
            hp: 140,
            attack: 70,
            defense: 45,
            "special-attack": 85,
            "special-defense": 50,
            speed: 45,
        },
        height: 10,
        weight: 120,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/40.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/40.png",
    },
    {
        id: 41,
        name: "zubat",
        types: ["poison", "flying"],
        stats: {
            hp: 40,
            attack: 45,
            defense: 35,
            "special-attack": 30,
            "special-defense": 40,
            speed: 55,
        },
        height: 8,
        weight: 75,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/41.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png",
    },
    {
        id: 42,
        name: "golbat",
        types: ["poison", "flying"],
        stats: {
            hp: 75,
            attack: 80,
            defense: 70,
            "special-attack": 65,
            "special-defense": 75,
            speed: 90,
        },
        height: 16,
        weight: 550,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/42.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png",
    },
    {
        id: 43,
        name: "oddish",
        types: ["grass", "poison"],
        stats: {
            hp: 45,
            attack: 50,
            defense: 55,
            "special-attack": 75,
            "special-defense": 65,
            speed: 30,
        },
        height: 5,
        weight: 54,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/43.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png",
    },
    {
        id: 44,
        name: "gloom",
        types: ["grass", "poison"],
        stats: {
            hp: 60,
            attack: 65,
            defense: 70,
            "special-attack": 85,
            "special-defense": 75,
            speed: 40,
        },
        height: 8,
        weight: 86,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/44.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/44.png",
    },
    {
        id: 45,
        name: "vileplume",
        types: ["grass", "poison"],
        stats: {
            hp: 75,
            attack: 80,
            defense: 85,
            "special-attack": 110,
            "special-defense": 90,
            speed: 50,
        },
        height: 12,
        weight: 186,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/45.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/45.png",
    },
    {
        id: 46,
        name: "paras",
        types: ["bug", "grass"],
        stats: {
            hp: 35,
            attack: 70,
            defense: 55,
            "special-attack": 45,
            "special-defense": 55,
            speed: 25,
        },
        height: 3,
        weight: 54,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/46.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/46.png",
    },
    {
        id: 47,
        name: "parasect",
        types: ["bug", "grass"],
        stats: {
            hp: 60,
            attack: 95,
            defense: 80,
            "special-attack": 60,
            "special-defense": 80,
            speed: 30,
        },
        height: 10,
        weight: 295,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/47.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/47.png",
    },
    {
        id: 48,
        name: "venonat",
        types: ["bug", "poison"],
        stats: {
            hp: 60,
            attack: 55,
            defense: 50,
            "special-attack": 40,
            "special-defense": 55,
            speed: 45,
        },
        height: 10,
        weight: 300,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/48.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/48.png",
    },
    {
        id: 49,
        name: "venomoth",
        types: ["bug", "poison"],
        stats: {
            hp: 70,
            attack: 65,
            defense: 60,
            "special-attack": 90,
            "special-defense": 75,
            speed: 90,
        },
        height: 15,
        weight: 125,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/49.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/49.png",
    },
    {
        id: 50,
        name: "diglett",
        types: ["ground"],
        stats: {
            hp: 10,
            attack: 55,
            defense: 25,
            "special-attack": 35,
            "special-defense": 45,
            speed: 95,
        },
        height: 2,
        weight: 8,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/50.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png",
    },
    {
        id: 51,
        name: "dugtrio",
        types: ["ground"],
        stats: {
            hp: 35,
            attack: 100,
            defense: 50,
            "special-attack": 50,
            "special-defense": 70,
            speed: 120,
        },
        height: 7,
        weight: 333,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/51.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png",
    },
    {
        id: 52,
        name: "meowth",
        types: ["normal"],
        stats: {
            hp: 40,
            attack: 45,
            defense: 35,
            "special-attack": 40,
            "special-defense": 40,
            speed: 90,
        },
        height: 4,
        weight: 42,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/52.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png",
    },
    {
        id: 53,
        name: "persian",
        types: ["normal"],
        stats: {
            hp: 65,
            attack: 70,
            defense: 60,
            "special-attack": 65,
            "special-defense": 65,
            speed: 115,
        },
        height: 10,
        weight: 320,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/53.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png",
    },
    {
        id: 54,
        name: "psyduck",
        types: ["water"],
        stats: {
            hp: 50,
            attack: 52,
            defense: 48,
            "special-attack": 65,
            "special-defense": 50,
            speed: 55,
        },
        height: 8,
        weight: 196,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/54.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png",
    },
    {
        id: 55,
        name: "golduck",
        types: ["water"],
        stats: {
            hp: 80,
            attack: 82,
            defense: 78,
            "special-attack": 95,
            "special-defense": 80,
            speed: 85,
        },
        height: 17,
        weight: 766,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/55.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png",
    },
    {
        id: 56,
        name: "mankey",
        types: ["fighting"],
        stats: {
            hp: 40,
            attack: 80,
            defense: 35,
            "special-attack": 35,
            "special-defense": 45,
            speed: 70,
        },
        height: 5,
        weight: 280,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/56.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png",
    },
    {
        id: 57,
        name: "primeape",
        types: ["fighting"],
        stats: {
            hp: 65,
            attack: 105,
            defense: 60,
            "special-attack": 60,
            "special-defense": 70,
            speed: 95,
        },
        height: 10,
        weight: 320,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/57.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/57.png",
    },
    {
        id: 58,
        name: "growlithe",
        types: ["fire"],
        stats: {
            hp: 55,
            attack: 70,
            defense: 45,
            "special-attack": 70,
            "special-defense": 50,
            speed: 60,
        },
        height: 7,
        weight: 190,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/58.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png",
    },
    {
        id: 59,
        name: "arcanine",
        types: ["fire"],
        stats: {
            hp: 90,
            attack: 110,
            defense: 80,
            "special-attack": 100,
            "special-defense": 80,
            speed: 95,
        },
        height: 19,
        weight: 1550,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/59.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png",
    },
    {
        id: 60,
        name: "poliwag",
        types: ["water"],
        stats: {
            hp: 40,
            attack: 50,
            defense: 40,
            "special-attack": 40,
            "special-defense": 40,
            speed: 90,
        },
        height: 6,
        weight: 124,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/60.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png",
    },
    {
        id: 61,
        name: "poliwhirl",
        types: ["water"],
        stats: {
            hp: 65,
            attack: 65,
            defense: 65,
            "special-attack": 50,
            "special-defense": 50,
            speed: 90,
        },
        height: 10,
        weight: 200,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/61.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/61.png",
    },
    {
        id: 62,
        name: "poliwrath",
        types: ["water", "fighting"],
        stats: {
            hp: 90,
            attack: 95,
            defense: 95,
            "special-attack": 70,
            "special-defense": 90,
            speed: 70,
        },
        height: 13,
        weight: 540,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/62.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/62.png",
    },
    {
        id: 63,
        name: "abra",
        types: ["psychic"],
        stats: {
            hp: 25,
            attack: 20,
            defense: 15,
            "special-attack": 105,
            "special-defense": 55,
            speed: 90,
        },
        height: 9,
        weight: 195,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/63.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png",
    },
    {
        id: 64,
        name: "kadabra",
        types: ["psychic"],
        stats: {
            hp: 40,
            attack: 35,
            defense: 30,
            "special-attack": 120,
            "special-defense": 70,
            speed: 105,
        },
        height: 13,
        weight: 565,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/64.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png",
    },
    {
        id: 65,
        name: "alakazam",
        types: ["psychic"],
        stats: {
            hp: 55,
            attack: 50,
            defense: 45,
            "special-attack": 135,
            "special-defense": 95,
            speed: 120,
        },
        height: 15,
        weight: 480,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/65.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png",
    },
    {
        id: 66,
        name: "machop",
        types: ["fighting"],
        stats: {
            hp: 70,
            attack: 80,
            defense: 50,
            "special-attack": 35,
            "special-defense": 35,
            speed: 35,
        },
        height: 8,
        weight: 195,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/66.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png",
    },
    {
        id: 67,
        name: "machoke",
        types: ["fighting"],
        stats: {
            hp: 80,
            attack: 100,
            defense: 70,
            "special-attack": 50,
            "special-defense": 60,
            speed: 45,
        },
        height: 15,
        weight: 705,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/67.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png",
    },
    {
        id: 68,
        name: "machamp",
        types: ["fighting"],
        stats: {
            hp: 90,
            attack: 130,
            defense: 80,
            "special-attack": 65,
            "special-defense": 85,
            speed: 55,
        },
        height: 16,
        weight: 1300,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/68.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png",
    },
    {
        id: 69,
        name: "bellsprout",
        types: ["grass", "poison"],
        stats: {
            hp: 50,
            attack: 75,
            defense: 35,
            "special-attack": 70,
            "special-defense": 30,
            speed: 40,
        },
        height: 7,
        weight: 40,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/69.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png",
    },
    {
        id: 70,
        name: "weepinbell",
        types: ["grass", "poison"],
        stats: {
            hp: 65,
            attack: 90,
            defense: 50,
            "special-attack": 85,
            "special-defense": 45,
            speed: 55,
        },
        height: 10,
        weight: 64,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/70.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png",
    },
    {
        id: 71,
        name: "victreebel",
        types: ["grass", "poison"],
        stats: {
            hp: 80,
            attack: 105,
            defense: 65,
            "special-attack": 100,
            "special-defense": 70,
            speed: 70,
        },
        height: 17,
        weight: 155,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/71.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png",
    },
    {
        id: 72,
        name: "tentacool",
        types: ["water", "poison"],
        stats: {
            hp: 40,
            attack: 40,
            defense: 35,
            "special-attack": 50,
            "special-defense": 100,
            speed: 70,
        },
        height: 9,
        weight: 455,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/72.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png",
    },
    {
        id: 73,
        name: "tentacruel",
        types: ["water", "poison"],
        stats: {
            hp: 80,
            attack: 70,
            defense: 65,
            "special-attack": 80,
            "special-defense": 120,
            speed: 100,
        },
        height: 16,
        weight: 550,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/73.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png",
    },
    {
        id: 74,
        name: "geodude",
        types: ["rock", "ground"],
        stats: {
            hp: 40,
            attack: 80,
            defense: 100,
            "special-attack": 30,
            "special-defense": 30,
            speed: 20,
        },
        height: 4,
        weight: 200,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/74.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png",
    },
    {
        id: 75,
        name: "graveler",
        types: ["rock", "ground"],
        stats: {
            hp: 55,
            attack: 95,
            defense: 115,
            "special-attack": 45,
            "special-defense": 45,
            speed: 35,
        },
        height: 10,
        weight: 1050,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/75.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png",
    },
    {
        id: 76,
        name: "golem",
        types: ["rock", "ground"],
        stats: {
            hp: 80,
            attack: 120,
            defense: 130,
            "special-attack": 55,
            "special-defense": 65,
            speed: 45,
        },
        height: 14,
        weight: 3000,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/76.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png",
    },
    {
        id: 77,
        name: "ponyta",
        types: ["fire"],
        stats: {
            hp: 50,
            attack: 85,
            defense: 55,
            "special-attack": 65,
            "special-defense": 65,
            speed: 90,
        },
        height: 10,
        weight: 300,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/77.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/77.png",
    },
    {
        id: 78,
        name: "rapidash",
        types: ["fire"],
        stats: {
            hp: 65,
            attack: 100,
            defense: 70,
            "special-attack": 80,
            "special-defense": 80,
            speed: 105,
        },
        height: 17,
        weight: 950,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/78.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/78.png",
    },
    {
        id: 79,
        name: "slowpoke",
        types: ["water", "psychic"],
        stats: {
            hp: 90,
            attack: 65,
            defense: 65,
            "special-attack": 40,
            "special-defense": 40,
            speed: 15,
        },
        height: 12,
        weight: 360,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/79.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png",
    },
    {
        id: 80,
        name: "slowbro",
        types: ["water", "psychic"],
        stats: {
            hp: 95,
            attack: 75,
            defense: 110,
            "special-attack": 100,
            "special-defense": 80,
            speed: 30,
        },
        height: 16,
        weight: 785,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/80.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png",
    },
    {
        id: 81,
        name: "magnemite",
        types: ["electric", "steel"],
        stats: {
            hp: 25,
            attack: 35,
            defense: 70,
            "special-attack": 95,
            "special-defense": 55,
            speed: 45,
        },
        height: 3,
        weight: 60,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/81.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png",
    },
    {
        id: 82,
        name: "magneton",
        types: ["electric", "steel"],
        stats: {
            hp: 50,
            attack: 60,
            defense: 95,
            "special-attack": 120,
            "special-defense": 70,
            speed: 70,
        },
        height: 10,
        weight: 600,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/82.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/82.png",
    },
    {
        id: 83,
        name: "farfetch'd",
        types: ["normal", "flying"],
        stats: {
            hp: 52,
            attack: 90,
            defense: 55,
            "special-attack": 58,
            "special-defense": 62,
            speed: 60,
        },
        height: 8,
        weight: 150,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/83.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/83.png",
    },
    {
        id: 84,
        name: "doduo",
        types: ["normal", "flying"],
        stats: {
            hp: 35,
            attack: 85,
            defense: 45,
            "special-attack": 35,
            "special-defense": 35,
            speed: 75,
        },
        height: 14,
        weight: 392,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/84.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png",
    },
    {
        id: 85,
        name: "dodrio",
        types: ["normal", "flying"],
        stats: {
            hp: 60,
            attack: 110,
            defense: 70,
            "special-attack": 60,
            "special-defense": 60,
            speed: 110,
        },
        height: 18,
        weight: 852,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/85.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png",
    },
    {
        id: 86,
        name: "seel",
        types: ["water"],
        stats: {
            hp: 65,
            attack: 45,
            defense: 55,
            "special-attack": 45,
            "special-defense": 70,
            speed: 45,
        },
        height: 11,
        weight: 900,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/86.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/86.png",
    },
    {
        id: 87,
        name: "dewgong",
        types: ["water", "ice"],
        stats: {
            hp: 90,
            attack: 70,
            defense: 80,
            "special-attack": 70,
            "special-defense": 95,
            speed: 70,
        },
        height: 17,
        weight: 1200,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/87.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/87.png",
    },
    {
        id: 88,
        name: "grimer",
        types: ["poison"],
        stats: {
            hp: 80,
            attack: 80,
            defense: 50,
            "special-attack": 40,
            "special-defense": 50,
            speed: 25,
        },
        height: 9,
        weight: 300,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/88.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png",
    },
    {
        id: 89,
        name: "muk",
        types: ["poison"],
        stats: {
            hp: 105,
            attack: 105,
            defense: 75,
            "special-attack": 65,
            "special-defense": 100,
            speed: 50,
        },
        height: 12,
        weight: 300,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/89.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/89.png",
    },
    {
        id: 90,
        name: "shellder",
        types: ["water"],
        stats: {
            hp: 30,
            attack: 65,
            defense: 100,
            "special-attack": 45,
            "special-defense": 25,
            speed: 40,
        },
        height: 3,
        weight: 40,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/90.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png",
    },
    {
        id: 91,
        name: "cloyster",
        types: ["water", "ice"],
        stats: {
            hp: 50,
            attack: 95,
            defense: 180,
            "special-attack": 85,
            "special-defense": 45,
            speed: 70,
        },
        height: 15,
        weight: 1325,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/91.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png",
    },
    {
        id: 92,
        name: "gastly",
        types: ["ghost", "poison"],
        stats: {
            hp: 30,
            attack: 35,
            defense: 30,
            "special-attack": 100,
            "special-defense": 35,
            speed: 80,
        },
        height: 13,
        weight: 1,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/92.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png",
    },
    {
        id: 93,
        name: "haunter",
        types: ["ghost", "poison"],
        stats: {
            hp: 45,
            attack: 50,
            defense: 45,
            "special-attack": 115,
            "special-defense": 55,
            speed: 95,
        },
        height: 16,
        weight: 1,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/93.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png",
    },
    {
        id: 94,
        name: "gengar",
        types: ["ghost", "poison"],
        stats: {
            hp: 60,
            attack: 65,
            defense: 60,
            "special-attack": 130,
            "special-defense": 75,
            speed: 110,
        },
        height: 15,
        weight: 405,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/94.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png",
    },
    {
        id: 95,
        name: "onix",
        types: ["rock", "ground"],
        stats: {
            hp: 35,
            attack: 45,
            defense: 160,
            "special-attack": 30,
            "special-defense": 45,
            speed: 70,
        },
        height: 88,
        weight: 2100,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/95.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png",
    },
    {
        id: 96,
        name: "drowzee",
        types: ["psychic"],
        stats: {
            hp: 60,
            attack: 48,
            defense: 45,
            "special-attack": 43,
            "special-defense": 90,
            speed: 42,
        },
        height: 10,
        weight: 324,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/96.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png",
    },
    {
        id: 97,
        name: "hypno",
        types: ["psychic"],
        stats: {
            hp: 85,
            attack: 73,
            defense: 70,
            "special-attack": 73,
            "special-defense": 115,
            speed: 67,
        },
        height: 16,
        weight: 756,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/97.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png",
    },
    {
        id: 98,
        name: "krabby",
        types: ["water"],
        stats: {
            hp: 30,
            attack: 105,
            defense: 90,
            "special-attack": 25,
            "special-defense": 25,
            speed: 50,
        },
        height: 4,
        weight: 65,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/98.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png",
    },
    {
        id: 99,
        name: "kingler",
        types: ["water"],
        stats: {
            hp: 55,
            attack: 130,
            defense: 115,
            "special-attack": 50,
            "special-defense": 50,
            speed: 75,
        },
        height: 13,
        weight: 600,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/99.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png",
    },
    {
        id: 100,
        name: "voltorb",
        types: ["electric"],
        stats: {
            hp: 40,
            attack: 30,
            defense: 50,
            "special-attack": 55,
            "special-defense": 55,
            speed: 100,
        },
        height: 5,
        weight: 104,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/100.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png",
    },
    {
        id: 101,
        name: "electrode",
        types: ["electric"],
        stats: {
            hp: 60,
            attack: 50,
            defense: 70,
            "special-attack": 80,
            "special-defense": 80,
            speed: 150,
        },
        height: 12,
        weight: 666,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/101.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/101.png",
    },
    {
        id: 102,
        name: "exeggcute",
        types: ["grass", "psychic"],
        stats: {
            hp: 60,
            attack: 40,
            defense: 80,
            "special-attack": 60,
            "special-defense": 45,
            speed: 40,
        },
        height: 4,
        weight: 25,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/102.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png",
    },
    {
        id: 103,
        name: "exeggutor",
        types: ["grass", "psychic"],
        stats: {
            hp: 95,
            attack: 95,
            defense: 85,
            "special-attack": 125,
            "special-defense": 75,
            speed: 55,
        },
        height: 20,
        weight: 1200,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/103.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png",
    },
    {
        id: 104,
        name: "cubone",
        types: ["ground"],
        stats: {
            hp: 50,
            attack: 50,
            defense: 95,
            "special-attack": 40,
            "special-defense": 50,
            speed: 35,
        },
        height: 4,
        weight: 65,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/104.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png",
    },
    {
        id: 105,
        name: "marowak",
        types: ["ground"],
        stats: {
            hp: 60,
            attack: 80,
            defense: 110,
            "special-attack": 50,
            "special-defense": 80,
            speed: 45,
        },
        height: 10,
        weight: 450,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/105.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png",
    },
    {
        id: 106,
        name: "hitmonlee",
        types: ["fighting"],
        stats: {
            hp: 50,
            attack: 120,
            defense: 53,
            "special-attack": 35,
            "special-defense": 110,
            speed: 87,
        },
        height: 15,
        weight: 498,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/106.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png",
    },
    {
        id: 107,
        name: "hitmonchan",
        types: ["fighting"],
        stats: {
            hp: 50,
            attack: 105,
            defense: 79,
            "special-attack": 35,
            "special-defense": 110,
            speed: 76,
        },
        height: 14,
        weight: 502,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/107.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png",
    },
    {
        id: 108,
        name: "lickitung",
        types: ["normal"],
        stats: {
            hp: 90,
            attack: 55,
            defense: 75,
            "special-attack": 60,
            "special-defense": 75,
            speed: 30,
        },
        height: 12,
        weight: 655,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/108.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/108.png",
    },
    {
        id: 109,
        name: "koffing",
        types: ["poison"],
        stats: {
            hp: 40,
            attack: 65,
            defense: 95,
            "special-attack": 60,
            "special-defense": 45,
            speed: 35,
        },
        height: 6,
        weight: 10,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/109.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png",
    },
    {
        id: 110,
        name: "weezing",
        types: ["poison"],
        stats: {
            hp: 65,
            attack: 90,
            defense: 120,
            "special-attack": 85,
            "special-defense": 70,
            speed: 60,
        },
        height: 12,
        weight: 95,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/110.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png",
    },
    {
        id: 111,
        name: "rhyhorn",
        types: ["ground", "rock"],
        stats: {
            hp: 80,
            attack: 85,
            defense: 95,
            "special-attack": 30,
            "special-defense": 30,
            speed: 25,
        },
        height: 10,
        weight: 1150,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/111.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png",
    },
    {
        id: 112,
        name: "rhydon",
        types: ["ground", "rock"],
        stats: {
            hp: 105,
            attack: 130,
            defense: 120,
            "special-attack": 45,
            "special-defense": 45,
            speed: 40,
        },
        height: 19,
        weight: 1200,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/112.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png",
    },
    {
        id: 113,
        name: "chansey",
        types: ["normal"],
        stats: {
            hp: 250,
            attack: 5,
            defense: 5,
            "special-attack": 35,
            "special-defense": 105,
            speed: 50,
        },
        height: 11,
        weight: 346,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/113.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png",
    },
    {
        id: 114,
        name: "tangela",
        types: ["grass"],
        stats: {
            hp: 65,
            attack: 55,
            defense: 115,
            "special-attack": 100,
            "special-defense": 40,
            speed: 60,
        },
        height: 10,
        weight: 350,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/114.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png",
    },
    {
        id: 115,
        name: "kangaskhan",
        types: ["normal"],
        stats: {
            hp: 105,
            attack: 95,
            defense: 80,
            "special-attack": 40,
            "special-defense": 80,
            speed: 90,
        },
        height: 22,
        weight: 800,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/115.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/115.png",
    },
    {
        id: 116,
        name: "horsea",
        types: ["water"],
        stats: {
            hp: 30,
            attack: 40,
            defense: 70,
            "special-attack": 70,
            "special-defense": 25,
            speed: 60,
        },
        height: 4,
        weight: 80,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/116.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/116.png",
    },
    {
        id: 117,
        name: "seadra",
        types: ["water"],
        stats: {
            hp: 55,
            attack: 65,
            defense: 95,
            "special-attack": 95,
            "special-defense": 45,
            speed: 85,
        },
        height: 12,
        weight: 250,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/117.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/117.png",
    },
    {
        id: 118,
        name: "goldeen",
        types: ["water"],
        stats: {
            hp: 45,
            attack: 67,
            defense: 60,
            "special-attack": 35,
            "special-defense": 50,
            speed: 63,
        },
        height: 6,
        weight: 150,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/118.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/118.png",
    },
    {
        id: 119,
        name: "seaking",
        types: ["water"],
        stats: {
            hp: 80,
            attack: 92,
            defense: 65,
            "special-attack": 65,
            "special-defense": 80,
            speed: 68,
        },
        height: 13,
        weight: 390,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/119.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/119.png",
    },
    {
        id: 120,
        name: "staryu",
        types: ["water"],
        stats: {
            hp: 30,
            attack: 45,
            defense: 55,
            "special-attack": 70,
            "special-defense": 55,
            speed: 85,
        },
        height: 8,
        weight: 345,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/120.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png",
    },
    {
        id: 121,
        name: "starmie",
        types: ["water", "psychic"],
        stats: {
            hp: 60,
            attack: 75,
            defense: 85,
            "special-attack": 100,
            "special-defense": 85,
            speed: 115,
        },
        height: 11,
        weight: 800,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/121.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png",
    },
    {
        id: 122,
        name: "mr-mime",
        types: ["psychic", "fairy"],
        stats: {
            hp: 40,
            attack: 45,
            defense: 65,
            "special-attack": 100,
            "special-defense": 120,
            speed: 90,
        },
        height: 13,
        weight: 545,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/122.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png",
    },
    {
        id: 123,
        name: "scyther",
        types: ["bug", "flying"],
        stats: {
            hp: 70,
            attack: 110,
            defense: 80,
            "special-attack": 55,
            "special-defense": 80,
            speed: 105,
        },
        height: 15,
        weight: 560,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/123.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/123.png",
    },
    {
        id: 124,
        name: "jynx",
        types: ["ice", "psychic"],
        stats: {
            hp: 65,
            attack: 50,
            defense: 35,
            "special-attack": 115,
            "special-defense": 95,
            speed: 95,
        },
        height: 14,
        weight: 406,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/124.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/124.png",
    },
    {
        id: 125,
        name: "electabuzz",
        types: ["electric"],
        stats: {
            hp: 65,
            attack: 83,
            defense: 57,
            "special-attack": 95,
            "special-defense": 85,
            speed: 105,
        },
        height: 11,
        weight: 300,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/125.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png",
    },
    {
        id: 126,
        name: "magmar",
        types: ["fire"],
        stats: {
            hp: 65,
            attack: 95,
            defense: 57,
            "special-attack": 100,
            "special-defense": 85,
            speed: 93,
        },
        height: 13,
        weight: 445,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/126.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/126.png",
    },
    {
        id: 127,
        name: "pinsir",
        types: ["bug"],
        stats: {
            hp: 65,
            attack: 125,
            defense: 100,
            "special-attack": 55,
            "special-defense": 70,
            speed: 85,
        },
        height: 15,
        weight: 550,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/127.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/127.png",
    },
    {
        id: 128,
        name: "tauros",
        types: ["normal"],
        stats: {
            hp: 75,
            attack: 100,
            defense: 95,
            "special-attack": 40,
            "special-defense": 70,
            speed: 110,
        },
        height: 14,
        weight: 884,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/128.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/128.png",
    },
    {
        id: 129,
        name: "magikarp",
        types: ["water"],
        stats: {
            hp: 20,
            attack: 10,
            defense: 55,
            "special-attack": 15,
            "special-defense": 20,
            speed: 80,
        },
        height: 9,
        weight: 100,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/129.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png",
    },
    {
        id: 130,
        name: "gyarados",
        types: ["water", "flying"],
        stats: {
            hp: 95,
            attack: 125,
            defense: 79,
            "special-attack": 60,
            "special-defense": 100,
            speed: 81,
        },
        height: 65,
        weight: 2350,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/130.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png",
    },
    {
        id: 131,
        name: "lapras",
        types: ["water", "ice"],
        stats: {
            hp: 130,
            attack: 85,
            defense: 80,
            "special-attack": 85,
            "special-defense": 95,
            speed: 60,
        },
        height: 25,
        weight: 2200,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/131.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png",
    },
    {
        id: 132,
        name: "ditto",
        types: ["normal"],
        stats: {
            hp: 48,
            attack: 48,
            defense: 48,
            "special-attack": 48,
            "special-defense": 48,
            speed: 48,
        },
        height: 3,
        weight: 40,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/132.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png",
    },
    {
        id: 133,
        name: "eevee",
        types: ["normal"],
        stats: {
            hp: 55,
            attack: 55,
            defense: 50,
            "special-attack": 45,
            "special-defense": 65,
            speed: 55,
        },
        height: 3,
        weight: 65,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/133.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png",
    },
    {
        id: 134,
        name: "vaporeon",
        types: ["water"],
        stats: {
            hp: 130,
            attack: 65,
            defense: 60,
            "special-attack": 110,
            "special-defense": 95,
            speed: 65,
        },
        height: 10,
        weight: 290,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/134.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png",
    },
    {
        id: 135,
        name: "jolteon",
        types: ["electric"],
        stats: {
            hp: 65,
            attack: 65,
            defense: 60,
            "special-attack": 110,
            "special-defense": 95,
            speed: 130,
        },
        height: 8,
        weight: 245,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/135.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png",
    },
    {
        id: 136,
        name: "flareon",
        types: ["fire"],
        stats: {
            hp: 65,
            attack: 130,
            defense: 60,
            "special-attack": 95,
            "special-defense": 110,
            speed: 65,
        },
        height: 9,
        weight: 250,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/136.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png",
    },
    {
        id: 137,
        name: "porygon",
        types: ["normal"],
        stats: {
            hp: 65,
            attack: 60,
            defense: 70,
            "special-attack": 85,
            "special-defense": 75,
            speed: 40,
        },
        height: 8,
        weight: 365,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/137.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/137.png",
    },
    {
        id: 138,
        name: "omanyte",
        types: ["rock", "water"],
        stats: {
            hp: 35,
            attack: 40,
            defense: 100,
            "special-attack": 90,
            "special-defense": 55,
            speed: 35,
        },
        height: 4,
        weight: 75,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/138.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png",
    },
    {
        id: 139,
        name: "omastar",
        types: ["rock", "water"],
        stats: {
            hp: 70,
            attack: 60,
            defense: 125,
            "special-attack": 115,
            "special-defense": 70,
            speed: 55,
        },
        height: 10,
        weight: 350,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/139.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png",
    },
    {
        id: 140,
        name: "kabuto",
        types: ["rock", "water"],
        stats: {
            hp: 30,
            attack: 80,
            defense: 90,
            "special-attack": 55,
            "special-defense": 45,
            speed: 55,
        },
        height: 5,
        weight: 115,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/140.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png",
    },
    {
        id: 141,
        name: "kabutops",
        types: ["rock", "water"],
        stats: {
            hp: 60,
            attack: 115,
            defense: 105,
            "special-attack": 65,
            "special-defense": 70,
            speed: 80,
        },
        height: 13,
        weight: 405,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/141.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png",
    },
    {
        id: 142,
        name: "aerodactyl",
        types: ["rock", "flying"],
        stats: {
            hp: 80,
            attack: 105,
            defense: 65,
            "special-attack": 60,
            "special-defense": 75,
            speed: 130,
        },
        height: 18,
        weight: 590,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/142.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/142.png",
    },
    {
        id: 143,
        name: "snorlax",
        types: ["normal"],
        stats: {
            hp: 160,
            attack: 110,
            defense: 65,
            "special-attack": 65,
            "special-defense": 110,
            speed: 30,
        },
        height: 21,
        weight: 4600,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/143.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png",
    },
    {
        id: 144,
        name: "articuno",
        types: ["ice", "flying"],
        stats: {
            hp: 90,
            attack: 85,
            defense: 100,
            "special-attack": 95,
            "special-defense": 125,
            speed: 85,
        },
        height: 17,
        weight: 554,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/144.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png",
    },
    {
        id: 145,
        name: "zapdos",
        types: ["electric", "flying"],
        stats: {
            hp: 90,
            attack: 90,
            defense: 85,
            "special-attack": 125,
            "special-defense": 90,
            speed: 100,
        },
        height: 16,
        weight: 526,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/145.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png",
    },
    {
        id: 146,
        name: "moltres",
        types: ["fire", "flying"],
        stats: {
            hp: 90,
            attack: 100,
            defense: 90,
            "special-attack": 125,
            "special-defense": 85,
            speed: 90,
        },
        height: 20,
        weight: 600,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/146.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png",
    },
    {
        id: 147,
        name: "dratini",
        types: ["dragon"],
        stats: {
            hp: 41,
            attack: 64,
            defense: 45,
            "special-attack": 50,
            "special-defense": 50,
            speed: 50,
        },
        height: 18,
        weight: 33,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/147.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png",
    },
    {
        id: 148,
        name: "dragonair",
        types: ["dragon"],
        stats: {
            hp: 61,
            attack: 84,
            defense: 65,
            "special-attack": 70,
            "special-defense": 70,
            speed: 70,
        },
        height: 40,
        weight: 165,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/148.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png",
    },
    {
        id: 149,
        name: "dragonite",
        types: ["dragon", "flying"],
        stats: {
            hp: 91,
            attack: 134,
            defense: 95,
            "special-attack": 100,
            "special-defense": 100,
            speed: 80,
        },
        height: 22,
        weight: 2100,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/149.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png",
    },
    {
        id: 150,
        name: "mewtwo",
        types: ["psychic"],
        stats: {
            hp: 106,
            attack: 110,
            defense: 90,
            "special-attack": 154,
            "special-defense": 90,
            speed: 130,
        },
        height: 20,
        weight: 1220,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/150.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png",
    },
    {
        id: 151,
        name: "mew",
        types: ["psychic"],
        stats: {
            hp: 100,
            attack: 100,
            defense: 100,
            "special-attack": 100,
            "special-defense": 100,
            speed: 100,
        },
        height: 4,
        weight: 40,
        sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png",
        shiny: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/151.png",
        official:
            "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png",
    },
];
