export const sprites = {
    bug: "https://archives.bulbagarden.net/media/upload/9/9c/BugIC_BDSP.png",
    dark: "https://archives.bulbagarden.net/media/upload/b/b9/DarkIC_BDSP.png",
    dragon: "https://archives.bulbagarden.net/media/upload/c/c7/DragonIC_BDSP.png",
    electric: "https://archives.bulbagarden.net/media/upload/c/c1/ElectricIC_BDSP.png",
    fairy: "https://archives.bulbagarden.net/media/upload/d/d6/FairyIC_BDSP.png",
    fighting: "https://archives.bulbagarden.net/media/upload/3/35/FightingIC_BDSP.png",
    fire: "https://archives.bulbagarden.net/media/upload/b/b1/FireIC_BDSP.png",
    flying: "https://archives.bulbagarden.net/media/upload/0/03/FlyingIC_BDSP.png",
    ghost: "https://archives.bulbagarden.net/media/upload/4/45/GhostIC_BDSP.png",
    grass: "https://archives.bulbagarden.net/media/upload/a/ad/GrassIC_BDSP.png",
    ground: "https://archives.bulbagarden.net/media/upload/b/bd/GroundIC_BDSP.png",
    ice: "https://archives.bulbagarden.net/media/upload/1/11/IceIC_BDSP.png",
    normal: "https://archives.bulbagarden.net/media/upload/8/89/NormalIC_BDSP.png",
    poison: "https://archives.bulbagarden.net/media/upload/8/8b/PoisonIC_BDSP.png",
    psychic: "https://archives.bulbagarden.net/media/upload/6/68/PsychicIC_BDSP.png",
    rock: "https://archives.bulbagarden.net/media/upload/9/98/RockIC_BDSP.png",
    steel: "https://archives.bulbagarden.net/media/upload/5/5f/SteelIC_BDSP.png",
    water: "https://archives.bulbagarden.net/media/upload/2/2b/WaterIC_BDSP.png",
};
export const types = [
    "any",
    "bug",
    "dark",
    "dragon",
    "electric",
    "fairy",
    "fighting",
    "fire",
    "flying",
    "ghost",
    "grass",
    "ground",
    "ice",
    "normal",
    "poison",
    "psychic",
    "rock",
    "steel",
    "water",
];
